-- Manticore 纯服务端向量检索：为 content 配置 float_vector + auto-embeddings
-- 目标：应用端只传“查询文本”，由 Manticore 生成查询向量并做 knn 检索
--
-- 重要提醒：
-- 1) float_vector 只能在 real-time table（RT table）里使用；普通 plain table 不支持。
-- 2) MODEL_NAME 决定向量维度与语义空间；你必须保证入库与查询使用同一个配置。
-- 3) 如果你已有数据，推荐“新建 RT 表 + 复制文本字段插入”，不要直接改坏旧表。
--
-- 示例：新建 RT 表 products_rt（字段名按你业务调整）
-- CREATE TABLE products_rt (
--     link TEXT,
--     link_md5 TEXT,
--     publish_time TIMESTAMP,
--     source TEXT,
--     fetch_time TIMESTAMP,
--     title TEXT,
--     content TEXT,
--     keywords TEXT,
--
--     content_vector FLOAT_VECTOR
--         KNN_TYPE='hnsw'
--         HNSW_SIMILARITY='cosine'
--         MODEL_NAME='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'
--         FROM='content'
-- );
--
-- 复制旧数据（只插入文本字段；Manticore 会自动生成 content_vector）
-- INSERT INTO products_rt (link, link_md5, publish_time, source, fetch_time, title, content, keywords)
-- SELECT link, link_md5, publish_time, source, fetch_time, title, content, keywords
-- FROM products;
--
-- 应用配置：
--   MANTICORE_TABLE=products_rt
--   MANTICORE_VECTOR_FIELD=content_vector
--
-- 参见官方 KNN / Auto-embeddings 文档。
